name: shamcode
title: shamcode | for the tech suvvy
description: The official website for gulthe SHAMCODE tech channel.
tags:
  - blog
  - technology
  - tech
  - review
  - download
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: shammulwa@gmail.com
disqus_username: shamulwa
